version: "3"

services:
  appdb:
    image: postgres:latest
    container_name: "hinataBlogContainer"
    environment:
      - POSTGRES_USER=hinata
      - POSTGRES_PASSWORD=hinata
      - POSTGRES_DB=hinataBlogDb
    ports:
      - "5432:5432"
    volumes:
      - database:/var/lib/postgresql/data

volumes:
  database:
    driver: local
